### ISSUE TITLE
Issue with "pcie_bw" when using with ROCm v5.7

### ISSUE THREAD

**Issue by AlbertaBeef** [ai-z/ai-z#1]
Using AIZ with ROCm v5.7 and AMD Radeon PRO W7900 GPU.

I see issue with "pcie_bw" functionnality, with following error output:

$ python3 -m aiz.aiz
   Detecting Hardware...
   WARNING:root:GPU[0]	: Unable to read /sys/class/drm/card0/device/pcie_bw
   Traceback (most recent call last):
     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
       return _run_code(code, main_globals, None,
     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
       exec(code, run_globals)
     File "/home/albertabeef/ROCm/ai-z/aiz/aiz.py", line 91, in <module>
       main(sys.argv)
     File "/home/albertabeef/ROCm/ai-z/aiz/aiz.py", line 72, in main
       DetectHardware()
     File "/home/albertabeef/ROCm/ai-z/aiz/hwinfo.py", line 20, in DetectHardware
       gpuDevices = ListAMDGPUDevices(False)
     File "/home/albertabeef/ROCm/ai-z/aiz/gpu_amd.py", line 343, in ListAMDGPUDevices
       gpus.append(AIZGPU_AMD(devicelist_sorted[i]))
     File "/home/albertabeef/ROCm/ai-z/aiz/gpu_amd.py", line 284, in __init__
       self.Sample()
     File "/home/albertabeef/ROCm/ai-z/aiz/gpu_amd.py", line 309, in Sample
       received = int(fsvals.split()[0])
   AttributeError: 'NoneType' object has no attribute 'split'

If I manually query "pcie_bw" system file:

   $ ls /sys/class/drm/card0/device/pcie_bw
   /sys/class/drm/card0/device/pcie_bw

   $ cat /sys/class/drm/card0/device/pcie_bw
   cat: /sys/class/drm/card0/device/pcie_bw: No data available

If I comment out the "pcie_bw" code from gpu_amd.py script, aiz.py script works.

   $ python3 -m aiz.aiz --version
   AI-Z version 0.3.1

   $ python3 -m aiz.aiz --showhwinfo
   Detecting Hardware...
   =======================================
   NUM_GPUS:1
   Name:card0
   Vram:46064.00 MB
   Fan Usage:20.000000 %
   =======================================
   CPU:CPU
   Cores:4
   Threads:8
   Mem:64042.554688 MB

   $ python3 -m aiz.aiz

... very cool, thanks !

**Comment by MatPoliquin** [comment]
Thanks for the feedback, not sure when I will have time to check this out but meanwhile you are welcome to submit a PR if you have time
